yojo-art/cherrypick

CHANGELOG_yojo.md
packages/frontend/src/scripts/clear-cache.ts

キャッシュクリアでfetchInstanceを強制

---

CHANGELOG_yojo.md
packages/backend/src/core/DriveService.ts

リモートユーザーにはファイルサイズ制限を適用しない

---

packages/frontend/src/pages/messaging/index.vue

チャット検索機能のUIを削除

---

CHANGELOG_yojo.md
package.json
packages/cherrypick-js/package.json

Release: 0.2.2(Develop)

---

packages/frontend/src/components/MkNote.vue
packages/frontend/src/components/MkNoteDetailed.vue
packages/frontend/src/components/MkUrlPreview.vue
packages/frontend/src/components/global/MkMisskeyFlavoredMarkdown.ts
packages/frontend/src/components/global/MkUrl.vue
packages/frontend/src/pages/clip.vue

リモートクリップ閲覧機能のフロントエンド改善

---

CHANGELOG_yojo.md
package.json
packages/cherrypick-js/package.json

Release: 0.3.0(Develop)

---

packages/backend/src/models/Meta.ts

fix: inquiryUrl

---

CHANGELOG_yojo.md
package.json
packages/cherrypick-js/package.json

Release: 0.3.1(Develop)

---

CHANGELOG_yojo.md
package.json
packages/cherrypick-js/package.json

Release: 0.3.2(Develop)

---

packages/frontend/src/pages/settings/general.vue
packages/frontend/src/pages/settings/preferences-backups.vue
packages/frontend/src/pages/settings/sounds-and-vibrations.vue
packages/frontend/src/pages/settings/timeline.vue
packages/frontend/src/scripts/sound.ts
packages/frontend/src/store.ts

チャンネル関係の設定を削除

---

CHANGELOG_yojo.md
packages/frontend/src/pages/tag.vue

ハッシュタグTLで投稿した後リロードしない

---

CHANGELOG_yojo.md
package.json
packages/cherrypick-js/package.json

Release: 0.3.3(Develop)

---

CHANGELOG_yojo.md
package.json
packages/cherrypick-js/package.json

Release: 0.3.4(Develop)

---

CHANGELOG_yojo.md

fix: changelog

---

CHANGELOG.md
CHANGELOG_CHERRYPICK.md
package.json
packages/cherrypick-js/package.json
packages/frontend/src/components/MkCode.core.vue

Merge 4.9.0

---

CHANGELOG_yojo.md
packages/frontend/src/components/MkTimeline.vue
packages/frontend/src/pages/settings/preferences-backups.vue
packages/frontend/src/pages/settings/timeline.vue
packages/frontend/src/pages/timeline.vue
packages/frontend/src/store.ts
packages/frontend/src/ui/deck/deck-store.ts
packages/frontend/src/ui/deck/tl-column.vue
packages/frontend/src/widgets/WidgetTimeline.vue

#54 の修正
TLウィジェットにメディアタイムライン追加
TLウィジェットでロール制限されたTLを選択肢から消す
TL上部アイコン表示の設定にチャンネルの残骸が残ってたから消す

メディアタイムライン設定の修正

---

CHANGELOG_yojo.md
package.json
packages/cherrypick-js/package.json

Release: 0.4.0(Develop)

---

CHANGELOG_yojo.md
package.json
packages/cherrypick-js/package.json

Release: 0.4.1(Develop)

---

packages/backend/test/e2e/endpoints.ts
packages/backend/test/e2e/move.ts
packages/backend/test/e2e/streaming.ts
packages/backend/test/e2e/timelines.ts

チャンネルのE2Eテスト削除

---

.config/docker_example.yml
.config/example.yml
CHANGELOG_yojo.md
packages/backend/src/GlobalModule.ts
packages/backend/src/config.ts
packages/backend/src/di-symbols.ts
packages/backend/src/server/HealthServerService.ts
packages/backend/src/server/api/endpoints/clips/notes.ts
packages/backend/src/server/api/endpoints/clips/show.ts
packages/backend/src/server/api/endpoints/users/clips.ts

redisForRemoteClipsをredisForRemoteApisに変更

---

locales/en-US.yml
locales/index.d.ts
locales/ja-JP.yml

fix: #274 
locales/index.d.ts
locales/ja-JP.yml

fix: missing locale

---

CHANGELOG_yojo.md
package.json
packages/cherrypick-js/package.json

Release: 0.5.0(Develop)

---

CHANGELOG_yojo.md
packages/backend/src/core/activitypub/ApInboxService.ts

fix ApInboxService fromRelay

---

CHANGELOG_yojo.md
package.json
packages/cherrypick-js/package.json

Release: 0.5.1(Develop)

---

CHANGELOG_yojo.md
package.json
packages/backend/src/core/activitypub/ApInboxService.ts
packages/cherrypick-js/package.json

Cherrypick 4.10.0-rc.3
2024-08-13
-
-
- Fix: APリクエストannounceNoteを受け取れない問題を修正

Release: 0.5.1

---

packages/backend/src/core/activitypub/misc/contexts.ts

contexts.tsにyojoart:bannerを定義

---

packages/backend/src/core/activitypub/misc/contexts.ts

contexts.tsにyojoart:Gameを定義

---

packages/backend/src/server/api/endpoints/admin/unset-user-mutual-link.ts
packages/cherrypick-js/src/autogen/apiClientJSDoc.ts
packages/cherrypick-js/src/autogen/types.ts

unset-user-mutual-linkにsecureを追加

---

packages/backend/src/core/activitypub/models/ApPersonService.ts

ロール制限あるのにリモートユーザーに適用するの忘れてたから実装

リモートユーザーに相互リンク上限を適用

---

CHANGELOG_YOJO.md
packages/frontend/src/scripts/get-user-menu.ts

ユーザー概要の...からサーバー情報にリンクを追加する

---

CHANGELOG_YOJO.md
package.json
packages/cherrypick-js/package.json

Release: 1.0.0(Develop)

---

CHANGELOG_YOJO.md
package.json
packages/cherrypick-js/package.json

Release: 1.0.1(Develop)

---

locales/index.d.ts
locales/ja-JP.yml
packages/backend/src/core/entities/NotificationEntityService.ts
packages/backend/src/models/Notification.ts
packages/backend/src/models/json-schema/notification.ts
packages/backend/src/queue/processors/ScheduleNotePostProcessorService.ts
packages/backend/src/types.ts
packages/cherrypick-js/etc/cherrypick-js.api.md
packages/cherrypick-js/src/autogen/types.ts
packages/cherrypick-js/src/consts.ts
packages/frontend/src/components/MkNotification.vue
packages/frontend/src/const.ts
packages/sw/src/scripts/create-notification.ts

予約投稿に失敗した時に通知する

---

packages/frontend/src/pages/settings/privacy.vue

デフォルトの検索可能範囲が変更できない不具合を修正

---

CHANGELOG_YOJO.md
locales/index.d.ts
locales/ja-JP.yml

モデログにロケール追加した
ジョブキュー再試行すると虚無がモデログに出る

ロケール：ジョブキューを再試行

---

CHANGELOG_YOJO.md

Release: 1.2.0(Develop)

---

CHANGELOG_YOJO.md
package.json
packages/cherrypick-js/package.json

Release: 1.2.1(Develop)

---

CHANGELOG_YOJO.md
packages/frontend/src/pages/mfc-cheat-sheet.vue

MFMチートシートが何も表示されない不具合を修正する
なんか壊れてた
マージ事故かも？原因不明

MFMチートシートが表示できない不具合を修正

---

packages/frontend-embed/src/boot.ts
packages/frontend/src/boot/common.ts
packages/frontend/src/pages/admin/index.vue
packages/frontend/src/ui/_common_/navbar-for-mobile.vue
packages/frontend/src/ui/_common_/navbar.vue
packages/frontend/src/ui/classic.header.vue
packages/frontend/src/ui/classic.sidebar.vue
packages/frontend/src/ui/friendly/navbar-for-mobile.vue
packages/frontend/src/ui/friendly/navbar.vue
packages/sw/src/scripts/create-notification.ts

更新チェックでCherrypickの更新情報見てた箇所を修正
#565 の変更漏れ

更新チェックでCherrypickの更新情報見てた箇所を修正

---

CHANGELOG_YOJO.md
package.json
packages/cherrypick-js/package.json

Release: 1.2.2(Develop)

---

CHANGELOG_YOJO.md
packages/frontend/src/components/MkFileListForAdmin.vue

コンパネのファイルに絵文字として利用中ラベルを表示する

---

packages/backend/test-federation/test/fetch-outbox.test.ts

fetch-outboxの連合テストを追加

---

locales/index.d.ts
locales/ja-JP.yml
packages/frontend/src/components/MkGoogle.vue
packages/frontend/src/pages/settings/general.vue
packages/frontend/src/pages/settings/preferences-backups.vue
packages/frontend/src/store.ts

Reverts yojo-art/cherrypick#575

Revert "MFMの検索エンジンをユーザー設定で変える"

---

CHANGELOG_YOJO.md
packages/frontend/src/pages/settings/privacy.vue

検索可能範囲の設定UIを改善

---

CHANGELOG_YOJO.md
packages/backend/src/server/NodeinfoServerService.ts

kmyblue形式の対応機能情報を追加
kmyblueとの相互運用性が改善する
その他実装でも参照することができる(現時点でこの実装は参照しない)
resolve: #619

nodeinfoで対応する機能を示す

---

CHANGELOG_YOJO.md
package.json
packages/cherrypick-js/package.json

Release: 1.3.0(Develop)

---

.github/workflows/api-cherrypick-js.yml
.github/workflows/get-api-diff.yml
.github/workflows/lint.yml
.github/workflows/locale.yml
.github/workflows/on-release-created.yml
.github/workflows/storybook.yml
.github/workflows/test-backend.yml
.github/workflows/test-cherrypick-js.yml
.github/workflows/test-federation.yml
.github/workflows/test-frontend.yml
.github/workflows/test-production.yml
.github/workflows/validate-api-json.yml
CHANGELOG_YOJO.md
Dockerfile
packages/backend/test-federation/compose.tpl.yml
packages/backend/test-federation/compose.yml

Cherry-picked from https://github.com/misskey-dev/misskey/pull/15387
.github/workflows/api-cherrypick-js.yml
.github/workflows/test-backend.yml
.github/workflows/test-cherrypick-js.yml
.github/workflows/test-frontend.yml
CHANGELOG.md

fix(build): corepackのバグの回避

---

CHANGELOG_YOJO.md
package.json
packages/cherrypick-js/package.json

Release: 1.3.1(Develop)

---

CHANGELOG_YOJO.md

Release: 1.4.0(Develop)

---

CHANGELOG_YOJO.md
packages/frontend/src/pages/note.vue

アップストリームマージで事故ってたやつ直した
Fix: #671

ノート詳細から前後TL見る機能の修正

---

CHANGELOG_YOJO.md
packages/frontend/src/components/MkPostFormSimple.vue

返信用投稿フォームを通常投稿フォームと統一

---

CHANGELOG_YOJO.md
packages/frontend/src/components/MkMenu.vue

動いてた1.3.1時代のコードに戻した
1.4.0で壊れた
Fix: #678 
戻すより直したいけど何が悪いのかわからん

右クリックメニューにスクロールバーがある時、派生メニューで考慮されない不具合の修正

---

CHANGELOG_YOJO.md
package.json
packages/cherrypick-js/package.json

Release: 1.4.1(Develop)

---

CHANGELOG_YOJO.md
packages/backend/src/config.ts

Cherrypick/1.4.1 -> yojo-art/1.4.1
ブランディング

UserAgentをyojo-artに変更

---

packages/backend/src/core/activitypub/ApResolverService.ts
packages/backend/src/core/activitypub/misc/contexts.ts
packages/backend/src/core/activitypub/models/ApClipService.ts
packages/backend/src/core/activitypub/models/ApPersonService.ts
packages/backend/src/core/activitypub/type.ts

Peertubeのプレイリストをクリップとして見れるように
#618 
自動テストは無理じゃね...?

Peertubeのプレイリストをクリップとして見れるように

---

CHANGELOG_YOJO.md
packages/backend/src/core/QueueService.ts

制限されたインスタンス宛にチャットの既読を配送しない
Fix: #756 
#574 での考慮漏れ

制限されたインスタンスに既読を配送しない
