packages/backend/migration/1717644139656-addDirectSummalyProxy.js, packages/backend/src/models/Meta.ts, packages/backend/src/server/api/endpoints/admin/meta.ts, packages/backend/src/server/api/endpoints/admin/update-meta.ts, packages/backend/src/server/api/endpoints/meta.ts, packages/cherrypick-js/src/autogen/types.ts, packages/frontend/src/components/MkUrlPreview.vue, packages/frontend/src/pages/admin/settings.vue
close: #81 
サマリプロキシの実装によってはCORSエラーになるので設定で従来方式と直接接続方式を切り替えられるようにしてある
=> クライアントが直接サマリプロキシに接続するオプション

packages/frontend/src/pages/tag.vue
=> ハッシュタグTLを離れた時にchannelを切断

packages/frontend/src/components/global/MkCustomEmoji.vue, packages/frontend/src/pages/custom-emojis-manager.vue, packages/frontend/src/scripts/import-emoji.ts
close:#242
デフォルト値リモートから取得した値で埋めた編集ダイアログをインポート直後に表示する
更新せずダイアログを閉じるとリモートの値を無視した従来通りの動作になる
=> 絵文字インポート時に編集ダイアログを出す

CHANGELOG_yojo.md, locales/index.d.ts, locales/ja-JP.yml, packages/frontend/src/components/MkMediaImage.vue, packages/frontend/src/components/MkMediaVideo.vue, packages/frontend/src/scripts/check-r18.ts, packages/frontend/src/scripts/import-emoji.ts
close: #244 
NSFW=成人指定ではないという問題があるものの成人指定メディアを含むのでとりあえず出しとく
=> NSFWフラグの付いた画像と動画で年齢確認ダイアログを出す

CHANGELOG_yojo.md, packages/frontend/src/components/MkLink.vue, packages/frontend/src/components/MkUrlPreview.vue, packages/frontend/src/components/global/MkMisskeyFlavoredMarkdown.ts, packages/frontend/src/components/global/MkUrl.vue
fix: #318 
プレビューの生成に元のURLを使うようにした
=> リモートクリップURL書き換えの改善

packages/backend/src/core/activitypub/models/ApPersonService.ts
リモートユーザー作成前にドライブ登録しようとして失敗してたのを修正する
=> リモートユーザー作成後に相互リンク情報を登録

packages/backend/src/core/FetchInstanceMetadataService.ts, packages/backend/src/core/ReversiService.ts, packages/backend/src/core/activitypub/models/ApGameService.ts, packages/backend/src/server/NodeinfoServerService.ts
#378 の対応状況の公開部分。対応状況の確認部分は別PRで出す
semverにした都合で部分的実装はできない
後で機能ネゴシエーション追加するかも
バージョン末尾の-yojoは実装名
=> nodeinfoにリバーシ連合の機能レベルを含める

CHANGELOG_YOJO.md, locales/index.d.ts, locales/ja-JP.yml, packages/backend/migration/1724921022768-AddNodeinfoReversi.js, packages/backend/src/core/FetchInstanceMetadataService.ts, packages/backend/src/core/ReversiService.ts, packages/backend/src/core/activitypub/models/ApGameService.ts, packages/backend/src/core/entities/InstanceEntityService.ts, packages/backend/src/core/entities/MetaEntityService.ts, packages/backend/src/models/Instance.ts, packages/backend/src/models/json-schema/federation-instance.ts, packages/backend/src/models/json-schema/meta.ts, packages/cherrypick-js/src/autogen/types.ts, packages/frontend/src/components/MkInstanceCardMini.vue, packages/frontend/src/pages/instance-info.vue, packages/frontend/src/pages/reversi/index.vue
リモートサーバー情報にリバーシのバージョンを追加
リモートユーザーをリバーシに招待する時、相手のバージョンを確認する
相手のサーバーの対応状況を確認できるように
resolve: #378 
#379 で発生した正しく対戦設定まで進めない不具合を修正してある
=> サーバー情報にリバーシのバージョンを表示する

packages/backend/src/core/activitypub/ApRendererService.ts, packages/backend/src/core/activitypub/models/ApPersonService.ts
「追加情報」の欄に相互リンクのテキスト要素を含めた。ioフォーク相当
yojo-art仕様の拡張に対応している場合は画像を含む完全な表示に切り替わる
既存実装との互換性を改善する
develop版のyojo-artと連合した時変になるけどリリースしてないからいいよね？
=> 相互リンクに対応していない場合でもテキストが表示されるように

CHANGELOG_YOJO.md, package.json, packages/cherrypick-js/package.json
=> Release: 0.6.0(Develop)

CHANGELOG_YOJO.md, packages/frontend/src/pages/reversi/game.board.vue, packages/frontend/src/pages/reversi/game.setting.vue, packages/frontend/src/pages/reversi/game.vue
非ログインユーザーが戦績を見れるようになる
ローカルユーザーが参加してない対戦が見れないの不便
fix: #403
=> 非ログインでリバーシの戦績が見れるように

CHANGELOG_YOJO.md, packages/frontend/src/components/MkNoteDetailed.vue
ノート詳細の本文表示優先度を変更
アバターデコレーションが本文を覆い隠してしまう
resolve: #405
=> ノート詳細の本文表示優先度を変更

CHANGELOG_YOJO.md, locales/index.d.ts, locales/ja-JP.yml, package.json, packages/backend/src/server/api/endpoints/notes/translate.ts, packages/backend/src/server/api/endpoints/users/translate.ts, packages/backend/test/e2e/note.ts, packages/cherrypick-js/package.json, packages/frontend/src/components/MkNote.vue, packages/frontend/src/components/MkNoteDetailed.vue, packages/frontend/src/components/MkSubNoteContent.vue, packages/frontend/src/pages/reversi/game.board.vue, packages/frontend/src/pages/reversi/game.setting.vue, packages/frontend/src/pages/reversi/game.vue, packages/frontend/src/pages/settings/general.vue, packages/frontend/src/pages/settings/preferences-backups.vue, packages/frontend/src/pages/user/home.vue, packages/frontend/src/scripts/check-last-renote.ts, packages/frontend/src/scripts/get-note-menu.ts, packages/frontend/src/scripts/get-user-menu.ts, packages/frontend/src/store.ts
Cherrypick 4.11.1
2024-09-05
-
- Fix: 非ログインでリバーシの戦績が見れない不具合の修正 [#404](https://github.com/yojo-art/cherrypick/pull/404)
- Fix: 翻訳に失敗したとき読み込み中のままになるのを修正 [#407](https://github.com/yojo-art/cherrypick/pull/407)
- Fix: ノート詳細の本文表示優先度を変更 [#408](https://github.com/yojo-art/cherrypick/pull/408)
- Feat: 同じノートを連続してリノートしようとしたときに警告する設定を追加(設定→全般) [#409](https://github.com/yojo-art/cherrypick/pull/409)
- Enhance: ユーザー概要の...からサーバー情報にリンクを追加 [#406](https://github.com/yojo-art/cherrypick/pull/406)
-
-
=> Release: 1.0.0

CHANGELOG_YOJO.md, packages/frontend/src/components/MkInstanceStats.vue, packages/frontend/src/scripts/use-chart-tooltip.ts
=> チャートの連合グラフで割合を表示

packages/backend/migration/1726276463152-ClipFavoriteRemote.js, packages/backend/src/core/ClipService.ts, packages/backend/src/di-symbols.ts, packages/backend/src/models/ClipFavoriteRemote.ts, packages/backend/src/models/RepositoryModule.ts, packages/backend/src/models/_.ts, packages/backend/src/postgres.ts, packages/backend/src/server/api/endpoints/clips/favorite.ts, packages/backend/src/server/api/endpoints/clips/my-favorites.ts, packages/backend/src/server/api/endpoints/clips/show.ts, packages/backend/src/server/api/endpoints/clips/unfavorite.ts, packages/cherrypick-js/etc/cherrypick-js.api.md, packages/cherrypick-js/src/autogen/endpoint.ts, packages/cherrypick-js/src/autogen/entities.ts, packages/cherrypick-js/src/autogen/types.ts
リモートのクリップをお気に入りに登録できるようにした。
clips/my-favoritesのオプションでローカルのみ、リモートのみに絞る事もできる
resolve: #296 
デフォルト設定だとclips/my-favorites呼ばれるたびに2回DB読んでるから速度は悪そう
=> リモートクリップのお気に入り登録

packages/frontend/src/components/MkInstanceStats.vue, packages/frontend/src/pages/admin/overview.federation.vue, packages/frontend/src/pages/admin/overview.pie.vue
チャートの連合グラフでその他が割合計算に含まれてなかった
#437 の実装が悪かった
=> チャートの連合グラフでその他が割合計算に含まれない問題を修正

CHANGELOG_YOJO.md, packages/frontend/src/components/MkLink.vue, packages/frontend/src/components/MkUrlPreview.vue, packages/frontend/src/components/global/MkUrl.vue
リモートから添付されてきたクリップURLにホスト情報があればそれを優先する
fix: #459
=> リモートから添付されてきたクリップURLにホスト情報があると二重になる不具合を修正

packages/frontend/src/scripts/use-chart-tooltip.ts
Number("1,000")===NaNの問題を修正する
#437 で実装した表示が計算対象の数が1,000を超えてるとNaNになってしまう問題
=> 連合割合%の表示が1000件以上のインスタンスでNaNになる不具合の修正

packages/backend/src/core/activitypub/models/ApPersonService.ts
リモートユーザーの相互リンクの各要素にidを追加
ローカルユーザーの相互リンクにはidがあるので揃える
idが無いと一部のサードパーティクライアントがクラッシュする
リモートユーザー情報の更新でid再生成されるけどこれでいいの？
=> リモートユーザーの相互リンクの各要素にidを追加

CHANGELOG_YOJO.md, packages/backend/src/core/ClipService.ts, packages/backend/src/misc/remote-api-utils.ts, packages/backend/src/models/json-schema/clip.ts, packages/backend/src/server/api/endpoints/clips/show.ts, packages/backend/src/server/api/endpoints/users/clips.ts, packages/cherrypick-js/src/autogen/types.ts, packages/frontend/src/pages/clip.vue
リモートユーザーのクリップ説明文に含まれるメンションと絵文字をリモート仕様にした
絵文字の情報が無かったからノートと同じ仕様でAPIに追加してある
fix: #464 
リモートの絵文字情報をredisForRemoteApisに入れてるからメモリ消費が気になるかも
=> リモートクリップ説明文がローカル仕様になってる問題の修正

CHANGELOG_YOJO.md, packages/frontend/src/pages/user/index.files.vue
- 個人設定の「センシティブなメディアの表示」と「センシティブなメディアを開く時」の設定を反映させる
- センシティブであれば年齢確認ダイアログを表示する
- データセーバー設定を反映する
fix: #463 
ユーザープロフィールまとめて修正したけど分割した方がよかった？
=> ユーザー概要の「ファイル」の挙動を通常の添付ファイルに合わせる

CHANGELOG_YOJO.md, packages/frontend/src/components/MkNote.vue, packages/frontend/src/components/MkNoteDetailed.vue, packages/frontend/src/components/MkSubNoteContent.vue, packages/frontend/src/components/global/MkMisskeyFlavoredMarkdown.ts, packages/frontend/src/scripts/collapsed.ts
非ログイン時に動きのあるMFMを動かすか選べるようにした
非ログイン時でも選べたほうが便利
https://xn--vusz0j.art/notes/01JAEY70CJRZJ9EGXZYDW0XP57
設定はクライアントに保持する
=> 非ログイン時に動きのあるMFMを動かすか選べるように

packages/backend/src/core/AdvancedSearchService.ts, packages/backend/src/server/api/endpoints/i/notifications-grouped.ts, packages/backend/src/server/api/endpoints/i/notifications.ts
通知APIがページ境界で重複する問題の修正
fix: #493
=> 通知APIがページ境界で重複する問題の修正

CHANGELOG_YOJO.md, packages/backend/src/core/CustomEmojiService.ts
絵文字を登録する際にシステムユーザーとして再アップロード
登録したユーザーがアカウントを削除しても絵文字が消えないように
=> feat: 絵文字を登録する際にシステムユーザーとして再アップロード

CHANGELOG_YOJO.md, packages/frontend/src/pages/about.vue, packages/frontend/src/pages/official-tags.vue
definePageMetadataするかオプションにした
fix: #445
=> サーバー情報で公式タグを開いてもページタイトルを更新しない

CHANGELOG_YOJO.md, packages/frontend/src/pages/settings/privacy.vue
デフォルトの公開範囲の設定から連合なしを削除
連合なし機能は削除済、機能してない設定項目は紛らわしい
localStorageには残してある
=> デフォルトの公開範囲から連合なしを削除

packages/frontend/src/components/MkPostForm.vue
#440 で追加されたポップアップの位置を修正
変なところにダイアログ出てた
まーた変数名ミスってる
=> 投稿フォーム検索許可選択ポップアップの位置を修正

CHANGELOG_YOJO.md, package.json, packages/cherrypick-js/package.json
=> Release: 1.1.0(Develop)

CHANGELOG_YOJO.md, packages/backend/src/core/WebhookTestService.ts, packages/backend/src/models/json-schema/note.ts, packages/cherrypick-js/src/autogen/types.ts, packages/frontend/src/components/MkPostForm.vue, packages/frontend/src/components/MkPostFormSimple.vue
=> ノートを編集する時に検索許可範囲を記憶する

packages/backend/src/server/api/endpoints/admin/meta.ts, packages/cherrypick-js/src/autogen/types.ts, packages/frontend/src/pages/admin/settings.vue
ステータスページURLとサマリDirectAccessが変更できるよう修正
#549 で壊れた
なんか元から型定義忘れてた所書き足しといた
=> ステータスページURLとサマリDirectAccessを変更できない問題を修正

packages/frontend/src/scripts/get-user-menu.ts
ユーザー詳細の「サーバー情報」が重複してたのを片方削除
独自追加してたけどcherrypick側でも追加されて重複した
cherrypick側の実装を残した
=> ユーザー詳細「サーバー情報」の重複を修正

packages/frontend/src/components/MkNoteDetailed.vue
リノート/リプライされたノートの詳細が開けない事があった
バグ修正
=> ノート詳細が開けない場合がある不具合の修正

CHANGELOG_YOJO.md, packages/frontend/src/components/MkLink.vue, packages/frontend/src/components/MkUrlPreview.vue, packages/frontend/src/components/global/MkUrl.vue
リモートのplay/clipをローカルで見る機能はローカルのページが開くにも関わらず誤ったURLで外部リンク警告が出ていた問題を修正する
条件を満たしたリモートのplay/clipはローカルで利用できる。外部リンク警告は必要無い
=> リモートクリップ/リモートplay機能のURLで外部サイト警告が出る問題を修正

CHANGELOG_YOJO.md, packages/frontend/src/pages/timeline.vue
タイムラインオプションで表示切り替えするタブ選択肢からチャンネルを削除し、タグを追加
ユーザー設定画面と統一、存在しない項目を修正
=> タイムラインオプションで表示有無選択の選択肢を修正

CHANGELOG_YOJO.md, package.json, packages/backend/src/core/activitypub/models/ApOutboxFetchService.ts, packages/cherrypick-js/package.json, packages/frontend-embed/src/boot.ts, packages/frontend/src/boot/common.ts, packages/frontend/src/components/MkNoteDetailed.vue, packages/frontend/src/components/MkSubNoteContent.vue, packages/frontend/src/pages/admin/index.vue, packages/frontend/src/pages/mfc-cheat-sheet.vue, packages/frontend/src/pages/timeline.vue, packages/frontend/src/ui/_common_/navbar-for-mobile.vue, packages/frontend/src/ui/_common_/navbar.vue, packages/frontend/src/ui/classic.header.vue, packages/frontend/src/ui/classic.sidebar.vue, packages/frontend/src/ui/friendly/navbar-for-mobile.vue, packages/frontend/src/ui/friendly/navbar.vue, packages/sw/src/scripts/create-notification.ts
Cherrypick 4.13.0  
Misskey 2024.10.1
2024-12-27
-
- Fix: ノート詳細画面でリアクション出来ない [#584](https://github.com/yojo-art/cherrypick/pull/584)
- Fix: タイムラインオプションで表示有無選択の選択肢を修正 [#590](https://github.com/yojo-art/cherrypick/pull/590)
- Fix: MFMチートシートが表示できない不具合を修正 [#592](https://github.com/yojo-art/cherrypick/pull/592)
- Fix: 引用や返信のノートすべてに翻訳ボタンが表示される [#598](https://github.com/yojo-art/cherrypick/pull/598)
- Fix:`api/ap/fetch-outbox`でリノートしか取得されないのを修正 [#588](https://github.com/yojo-art/cherrypick/pull/588)
=> Release: 1.2.2

packages/backend/src/core/entities/NotificationEntityService.ts
=> グループ招待通知の修正

CHANGELOG_YOJO.md, packages/frontend/src/pages/user/index.timeline.vue
ユーザー詳細画面でログイン情報を取得する
fix: #594 
モデレーター権限でも見れる状態が正常らしい
=> 自分自身のリアクション一覧が公開設定に影響される問題を修正

CHANGELOG_YOJO.md, packages/frontend/src/pages/timeline.vue
=> 非ログインでローカル/グローバルタイムラインが表示できない不具合の修正

CHANGELOG_YOJO.md, packages/frontend/src/scripts/check-reaction-create.ts
`reaction.replace('@.', '')`
Fix: #679
=> ローカルのリアクションに相乗りする時の確認ダイアログを修正

CHANGELOG_YOJO.md, package.json, packages/cherrypick-js/package.json, packages/frontend/src/components/MkMenu.vue, packages/frontend/src/components/MkPostFormSimple.vue, packages/frontend/src/components/global/MkCustomEmoji.vue, packages/frontend/src/pages/note.vue, packages/frontend/src/scripts/check-reaction-create.ts
Cherrypick 4.15.0  
Misskey 2025.2.0
2025-03-29
- Fix: ノート詳細から前後TL見る機能の修正 [#677](https://github.com/yojo-art/cherrypick/pull/677)
- Fix: 返信用投稿フォームを通常投稿フォームと統一 [#676](https://github.com/yojo-art/cherrypick/pull/676)
- Fix: 右クリックメニューにスクロールバーがある時、派生メニューで考慮されない不具合の修正 [#680](https://github.com/yojo-art/cherrypick/pull/680)
- 問題が起きていた変更部分を1.3.1時点に戻しました
- Fix: ローカルのリアクションに相乗りする時の確認ダイアログを修正 [#682](https://github.com/yojo-art/cherrypick/pull/682)
- Fix: ノート内絵文字を付ける機能でローカルに無い絵文字は機能を非表示に [#683](https://github.com/yojo-art/cherrypick/pull/683)
- Fix: ノート詳細リアクションタブ内のリアクションボタンの画像部分にクリック判定が無い問題を修正 [#684](https://github.com/yojo-art/cherrypick/pull/684)
=> Release: 1.4.1
